---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: kibana-configmap
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    monitoring.ui.container.elasticsearch.enabled: true
    server.publicBaseUrl: "http://ux360-kibana.izzi.mx"
    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
      username: ${KIBANA_USER}
      password: ${KIBANA_PASSWORD}
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    app: kibana-service
spec:
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    name: webinterface
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.14.1
        ports:
        - containerPort: 5601
          name: webinterface
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-ingest.default.svc.cluster.local:9200"
        - name: KIBANA_USER
          value: "kibana_system"
        - name: KIBANA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kibana-system-pw
              key: password
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          readOnly: true
          subPath: kibana.yml
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1500m"
      volumes:
      - name: config
        configMap:
          name: kibana-config