apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  rules:
  - host: ux360.izzi.mx
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: kibana-service
            port:
              number: 5601